// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZYhuVrFl77Nir9FaeQS24PoR3_UbY1R0',
    appId: '1:92050507217:web:3d54cd5a371993da030cf0',
    messagingSenderId: '92050507217',
    projectId: 'tubes-mipro-e0108',
    authDomain: 'tubes-mipro-e0108.firebaseapp.com',
    databaseURL: 'https://tubes-mipro-e0108-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tubes-mipro-e0108.appspot.com',
    measurementId: 'G-F0V9ML6WV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoSGvGowMQVky9_25V6dD63dCw5tuojSY',
    appId: '1:92050507217:android:3bfeda092bbcc4ca030cf0',
    messagingSenderId: '92050507217',
    projectId: 'tubes-mipro-e0108',
    databaseURL: 'https://tubes-mipro-e0108-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tubes-mipro-e0108.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcKiCTumlTykkmGqiMiHBuxw6D0o-_R3I',
    appId: '1:92050507217:ios:0443fe5bbf77ebf2030cf0',
    messagingSenderId: '92050507217',
    projectId: 'tubes-mipro-e0108',
    databaseURL: 'https://tubes-mipro-e0108-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tubes-mipro-e0108.appspot.com',
    iosClientId: '92050507217-erbpkdtgk8blg2v8c24apq0eed89ml6c.apps.googleusercontent.com',
    iosBundleId: 'com.example.nadiku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcKiCTumlTykkmGqiMiHBuxw6D0o-_R3I',
    appId: '1:92050507217:ios:0443fe5bbf77ebf2030cf0',
    messagingSenderId: '92050507217',
    projectId: 'tubes-mipro-e0108',
    databaseURL: 'https://tubes-mipro-e0108-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tubes-mipro-e0108.appspot.com',
    iosClientId: '92050507217-erbpkdtgk8blg2v8c24apq0eed89ml6c.apps.googleusercontent.com',
    iosBundleId: 'com.example.nadiku',
  );
}
