// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIDzRHSa17SV-zp3x0w4z2WxnuTIfXD5o',
    appId: '1:767782292407:web:424733498638861798f632',
    messagingSenderId: '767782292407',
    projectId: 'tugas-akhir-42e52',
    authDomain: 'tugas-akhir-42e52.firebaseapp.com',
    storageBucket: 'tugas-akhir-42e52.appspot.com',
    measurementId: 'G-CH9BM9T15C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCga1iPqV4--cpaxuvbzWl2vyDykB5lOPU',
    appId: '1:767782292407:android:9c1d41cf59a00d6698f632',
    messagingSenderId: '767782292407',
    projectId: 'tugas-akhir-42e52',
    storageBucket: 'tugas-akhir-42e52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBED9W9ccDQMsYqWRETYmQ-xXfUmkME7lc',
    appId: '1:767782292407:ios:906bc5c5b5c5042c98f632',
    messagingSenderId: '767782292407',
    projectId: 'tugas-akhir-42e52',
    storageBucket: 'tugas-akhir-42e52.appspot.com',
    iosClientId: '767782292407-2n9h7gvlld9oalovb2401r59nembe0af.apps.googleusercontent.com',
    iosBundleId: 'com.example.nadiku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBED9W9ccDQMsYqWRETYmQ-xXfUmkME7lc',
    appId: '1:767782292407:ios:906bc5c5b5c5042c98f632',
    messagingSenderId: '767782292407',
    projectId: 'tugas-akhir-42e52',
    storageBucket: 'tugas-akhir-42e52.appspot.com',
    iosClientId: '767782292407-2n9h7gvlld9oalovb2401r59nembe0af.apps.googleusercontent.com',
    iosBundleId: 'com.example.nadiku',
  );
}
